"""Curated cooking steps for snacks inspired by The Lean Green Bean (paraphrased; not copied text)."""

LEAN_GREENBEAN_SNACK_STEPS: dict[str, list[str]] = {
    "Lemon Oat Energy Balls": [
        "Pulse oats in a food processor until partly broken down; pit dates if needed.",
        "Add lemon zest and juice, honey, coconut, chia, vanilla, and a pinch of salt; blend until the mix sticks when squeezed.",
        "Roll into tight balls; chill 20–30 minutes so they firm up.",
        "Store in the fridge up to a week or freeze for longer.",
    ],
    "Chewy Homemade Granola Bars": [
        "Line a pan with parchment. Heat butter, brown sugar, and honey until smooth; stir in vanilla and salt off heat.",
        "Fold in oats and almonds until evenly coated; press very firmly into the pan.",
        "Bake at 325°F (165°C) until golden at the edges; cool completely before slicing.",
        "Wrap bars for grab-and-go snacks.",
    ],
    "Greek Yogurt Ranch Dip": [
        "Stir Greek yogurt with garlic powder, onion powder, dried dill, chives, salt, and pepper.",
        "Thin with a splash of lemon juice until dippable; taste and adjust seasoning.",
        "Chill 30 minutes for flavor to meld.",
        "Serve with cut vegetables or corn chips.",
    ],
    "Berry Yogurt Smoothie Snack": [
        "Add milk first, then berries, banana, yogurt, honey, vanilla, and ice.",
        "Blend until smooth; scrape down once if needed.",
        "Taste; add honey or a splash more milk to balance.",
        "Pour into a glass or insulated cup and drink soon.",
    ],
    "Turkey Cheese Apple Skewers": [
        "Cut turkey and cheese into cubes similar in size to apple chunks; toss apple with lemon juice to limit browning.",
        "Thread turkey, cheese, and apple onto small picks in repeating patterns.",
        "Season lightly with salt and pepper if you like.",
        "Serve immediately or pack chilled for the same day.",
    ],
    "Chocolate Avocado Pudding Cups": [
        "Scoop avocado into a blender with cocoa, pitted dates, maple syrup, vanilla, salt, and almond milk.",
        "Blend until completely silky; scrape the sides once.",
        "Spoon into cups; chill at least 30 minutes.",
        "Top with a few cocoa nibs or berries if you have them.",
    ],
    "Ranch Popcorn Snack": [
        "Pop kernels your usual way (stovetop with a lid or air popper).",
        "Toss warm popcorn with melted butter, nutritional yeast, garlic and onion powder, parsley, salt, and pepper.",
        "Shake the bowl until every kernel looks lightly coated.",
        "Serve warm; store leftovers loosely covered so it stays crisp.",
    ],
    "Microwave Egg Snack Sandwich": [
        "Beat eggs with salt and pepper; microwave in a shallow greased dish in short bursts until just set, folding once.",
        "Toast the English muffin; melt cheese on one half if you like.",
        "Layer spinach and the cooked egg; close the sandwich.",
        "Eat warm within a few minutes for best texture.",
    ],
    "Turkey Cheddar Lettuce Roll Ups": [
        "Pat turkey slices dry; lay lettuce leaves flat and trim thick ribs.",
        "Spread a thin layer of mustard and mayonnaise; add turkey and cheddar strips.",
        "Roll tightly like a cigar; secure with a pick if needed.",
        "Slice into pinwheels or eat whole; keep chilled until serving.",
    ],
    "Quick Yogurt Snack Bowl": [
        "Spoon Greek yogurt into a bowl.",
        "Top with berries, walnuts, cinnamon, honey, and a few chocolate chips.",
        "Stir gently or leave layered for crunch contrast.",
        "Serve right away.",
    ],
    "Veggie Black Bean Nachos": [
        "Spread corn chips on a microwave-safe plate; warm beans with cumin and a pinch of salt.",
        "Layer beans, cheese, and jalapeño; microwave in bursts until cheese melts.",
        "Finish with salsa, sour cream, green onions, and a squeeze of lime.",
        "Eat immediately while chips are still crisp.",
    ],
    "Sweet Potato White Bean Squares": [
        "Roast or microwave sweet potato until soft; mash with rinsed cannellini beans, oats, egg, maple syrup, cinnamon, vanilla, salt, and baking powder.",
        "Spread in a parchment-lined baking dish in an even layer.",
        "Bake at 350°F (175°C) until set and lightly golden; cool before cutting squares.",
        "Refrigerate extras; rewarm gently.",
    ],
    "Overnight Oats Snack Jars": [
        "Stir oats with milk, chia, yogurt, honey, vanilla, and salt in a jar.",
        "Fold in some berries; seal and refrigerate overnight.",
        "Stir in the morning; add more fresh berries on top.",
        "Eat cold or warm slightly in the microwave.",
    ],
    "Homemade Trail Mix": [
        "Combine almonds, pumpkin seeds, dried cranberries, chocolate chips, coconut, and a tiny pinch of salt.",
        "Toss in a sealed bag until evenly mixed.",
        "Portion into small containers for the week.",
        "Store airtight at room temperature.",
    ],
    "Hard-Boiled Egg Snack Pack": [
        "Cover eggs with cold water; bring to a boil, then simmer 9–11 minutes for firm yolks.",
        "Plunge into ice water; peel under cool running water.",
        "Halve or keep whole; season with everything seasoning and salt alongside tomatoes and cucumber.",
        "Pack chilled for the same day.",
    ],
    "Baked Blueberry Oatmeal Bars": [
        "Whisk eggs, milk, maple syrup, vanilla, salt, and cinnamon; fold in oats, baking powder, and blueberries.",
        "Pour into a greased or lined square pan.",
        "Bake at 350°F (175°C) until the center is set and the top is golden.",
        "Cool completely before cutting into bars.",
    ],
    "Apple Peanut Butter Nachos": [
        "Core and slice apples into thin wedges; arrange on a plate.",
        "Warm peanut butter slightly so it drizzles; zigzag over the apples.",
        "Scatter granola, mini chips, cinnamon, and a drizzle of honey.",
        "Serve immediately so apples stay crisp.",
    ],
    "Silver Dollar Pancake Snacks": [
        "Whisk dry ingredients; whisk wet separately; combine until just mixed.",
        "Heat a griddle with butter; drop small spoonfuls for silver-dollar size.",
        "Flip when bubbles form; cook until golden on both sides.",
        "Stack with berries and maple syrup or pack cooled pancakes for later.",
    ],
    "Cottage Cheese Snack Bowl": [
        "Spoon cottage cheese into a bowl.",
        "Top with halved tomatoes, cucumber, basil, olive oil, salt, and pepper.",
        "Add cracked black pepper generously if you like savory punch.",
        "Eat cold; great post-workout.",
    ],
    "Chicken Salad Snack Box": [
        "Dice cooked chicken; mix with Greek yogurt, mayonnaise, celery, halved grapes, lemon juice, salt, and pepper.",
        "Chill 20 minutes for flavors to blend.",
        "Pack with rice cakes in a divided container.",
        "Keep refrigerated until snack time.",
    ],
    "Pumpkin Peanut Butter Oat Squares": [
        "Stir pumpkin, peanut butter, oats, honey, cinnamon, vanilla, salt, and nutmeg until uniform.",
        "Press firmly into a lined dish in an even layer.",
        "Refrigerate at least 1 hour until firm enough to slice (no-bake bar).",
        "Cut into squares; store chilled up to a week.",
    ],
    "Air Fryer Chicken Bites": [
        "Cut tenders into bite-sized pieces; toss with oil, paprika, garlic powder, salt, and pepper.",
        "Air fry at 375°F (190°C) in a single layer, shaking once, until 165°F (74°C) inside and crisp outside.",
        "Whisk honey with a splash of gf soya sauce for a quick dip if you like.",
        "Rest 2 minutes before serving.",
    ],
    "Homemade Fruit Leather": [
        "Simmer apples and strawberries with honey, lemon, cinnamon, and a splash of water until very soft.",
        "Puree until smooth; spread thinly on a parchment-lined sheet pan.",
        "Dry in a low oven (about 140–170°F / 60–75°C) or dehydrator until leathery and not sticky in the center.",
        "Cool; slice into strips and roll with parchment backing.",
    ],
    "Turkey Lettuce Snack Wraps": [
        "Layer butter lettuce with turkey, provolone strips, and thin bell pepper.",
        "Drizzle Italian dressing; season lightly with salt and pepper.",
        "Roll tightly; halve on a bias for easier eating.",
        "Serve immediately so lettuce stays crisp.",
    ],
    "Crispy Sweet Potato Chips": [
        "Slice sweet potato very thinly with a mandoline if you have one; toss with cornstarch, then oil, paprika, garlic powder, salt, and pepper.",
        "Bake in a single layer at 400°F (200°C), flipping once, until crisp at the edges—watch closely near the end.",
        "Drain on a rack; sprinkle salt while warm.",
        "Best the day they are made.",
    ],
    "Frozen Yogurt Fruit Tubes": [
        "Blend Greek yogurt with mixed berries, honey, vanilla, and lemon until smooth.",
        "Pour into silicone popsicle molds or zip-top squeeze tubes designed for freezing.",
        "Freeze until solid.",
        "Thaw slightly before eating or pack in a cooler for a trip.",
    ],
}
