"""Recipe-style step lists for each meal (Eat? app). Used by main.meal_api_dict.

Regenerate with: python3 build_meal_steps.py
"""

MEAL_STEPS: dict[str, list[str]] = {
    "15-Minute Mezze Plate with Za'atar Pita": [
        "Gather and prep: pita bread, hummus, marinated artichoke hearts, roasted red peppers, olives, za'atar, olive oil, lemon, cucumber, feta cheese. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.",
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    '3-Ingredient Shredded Chicken Flautas': [
        'Gather and prep: chicken, flour tortillas, cheese, sour cream, salsa, vegetable oil, cumin, salt, green onions. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Air Fryer Chicken Bites': [
        'Cut tenders into bite-sized pieces; toss with oil, paprika, garlic powder, salt, and pepper.',
        'Air fry at 375°F (190°C) in a single layer, shaking once, until 165°F (74°C) inside and crisp outside.',
        'Whisk honey with a splash of gf soya sauce for a quick dip if you like.',
        'Rest 2 minutes before serving.',
    ],
    'Almond Butter Toast with Berries': [
        'Gather and prep: bread, almond butter, strawberries, honey, chia seeds, cinnamon, sea salt. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Ants on a Log': [
        'Gather and prep: celery, peanut butter, raisins, honey, salt, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Apple Cinnamon Oatmeal': [
        'Gather and prep: oats, apple, cinnamon, milk, maple syrup, salt, butter, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Simmer oats with liquid (water or milk) until creamy, stirring often so nothing sticks.',
        'Stir in spices, fruit, or sweeteners in the last few minutes to preserve texture.',
        'Spoon into bowls and finish with toppings from your list.',
    ],
    'Apple Peanut Butter Nachos': [
        'Core and slice apples into thin wedges; arrange on a plate.',
        'Warm peanut butter slightly so it drizzles; zigzag over the apples.',
        'Scatter granola, mini chips, cinnamon, and a drizzle of honey.',
        'Serve immediately so apples stay crisp.',
    ],
    'Avocado Egg Bowl': [
        'Gather and prep: avocado, eggs, rice, green onions, gf soya sauce, sesame oil, salt, sesame seeds, lime. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Avocado Toast with Egg': [
        'Gather and prep: bread, avocado, eggs, lemon, olive oil, salt, black pepper, red pepper flakes. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Avocado Tuna Salad Bowl': [
        'Gather and prep: tuna, avocado, cucumber, lemon, olive oil, red onion, mayonnaise, salt, black pepper, cilantro, celery. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Baked Bananas': [
        'Gather and prep: bananas, cinnamon, honey, nut butter, salt, butter, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    'Baked Blueberry Oatmeal Bars': [
        'Whisk eggs, milk, maple syrup, vanilla, salt, and cinnamon; fold in oats, baking powder, and blueberries.',
        'Pour into a greased or lined square pan.',
        'Bake at 350°F (175°C) until the center is set and the top is golden.',
        'Cool completely before cutting into bars.',
    ],
    'Baked Cod with Veggies': [
        'Gather and prep: cod, broccoli, carrots, lemon, olive oil, garlic, salt, black pepper, paprika, butter, fresh parsley. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    'Baked Salmon and Veggies': [
        'Gather and prep: salmon, broccoli, carrots, olive oil, lemon, garlic, salt, black pepper, dill. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    'Berry Protein Smoothie': [
        'Gather and prep: berries, protein powder, milk, banana, honey, ice, yogurt, chia seeds. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Add liquids first, then soft fruit or veg, powders, and ice (if using) so the blender can move freely.',
        'Blend until silky, scraping down once if a chunk sticks. Thin with a splash of milk or water if needed.',
        'Taste and adjust sweetness, citrus, or salt; pour into a glass or bowl and enjoy right away.',
    ],
    'Berry Yogurt Smoothie Snack': [
        'Add milk first, then berries, banana, yogurt, honey, vanilla, and ice.',
        'Blend until smooth; scrape down once if needed.',
        'Taste; add honey or a splash more milk to balance.',
        'Pour into a glass or insulated cup and drink soon.',
    ],
    'Black Bean Corn Rice Bowl': [
        'Gather and prep: black beans, corn, rice, avocado, lime, cilantro, salt, olive oil, cumin, chili powder, tomatoes, red onion. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Blueberry Pancakes': [
        'Gather and prep: flour, milk, eggs, blueberries, baking powder, sugar, salt, butter, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix wet and dry separately, then combine until *just* mixed—small lumps are fine for fluffy pancakes/waffles.',
        'Preheat griddle or waffle iron; grease lightly. Cook in batches until bubbles set on top and bottoms are golden.',
        'Stack and serve with toppings from your list while warm.',
    ],
    'Breakfast Burrito': [
        'Gather and prep: tortilla, eggs, potatoes, cheese, salsa, butter, salt, black pepper, cumin, sour cream. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Breakfast Quesadilla': [
        'Gather and prep: tortilla, eggs, cheese, spinach, butter, salt, black pepper, salsa. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Breakfast Sweet Potato Hash': [
        'Gather and prep: sweet potato, eggs, onion, bell peppers, olive oil, garlic, salt, black pepper, paprika, fresh parsley. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    "Broiler S'mores": [
        'Gather and prep: graham crackers, marshmallows, chocolate, butter, salt, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Buffalo Chicken Brie Bites': [
        'Gather and prep: chicken, brie, buffalo sauce, puff pastry, green onions, egg, salt, black pepper, blue cheese crumbles. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'Burrito Bowls': [
        'Cook rice; keep warm. Season chicken with cumin, chili powder, salt, and oil; grill or pan-sear to 165°F (74°C); rest and slice.',
        'Warm beans with a pinch of salt and cumin; warm or char corn briefly.',
        'Prep avocado, cilantro, lime, cheese, and sour cream.',
        'Layer rice, chicken, beans, corn, and toppings in bowls.',
        'Squeeze lime; sprinkle cilantro; serve.',
    ],
    'Cajun Shrimp Guacamole Bites': [
        'Gather and prep: shrimp, avocado, lime, cajun seasoning, cilantro, red onion, salt, garlic, tomato, tortilla chips. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'Caprese Salad': [
        'Gather and prep: tomatoes, mozzarella, basil, olive oil, balsamic, salt, black pepper, flaky sea salt. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Chewy Homemade Granola Bars': [
        'Line a pan with parchment. Heat butter, brown sugar, and honey until smooth; stir in vanilla and salt off heat.',
        'Fold in oats and almonds until evenly coated; press very firmly into the pan.',
        'Bake at 325°F (165°C) until golden at the edges; cool completely before slicing.',
        'Wrap bars for grab-and-go snacks.',
    ],
    'Chia Seed Pudding': [
        'Gather and prep: chia seeds, milk, honey, vanilla, berries, maple syrup, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Layer or soak components as the recipe suggests—chia often needs time in the fridge to thicken.',
        'Sweeten or spice to taste before final assembly.',
        'Top with fruit, granola, or nuts and serve chilled.',
    ],
    'Chicken Alfredo Pasta': [
        'Gather and prep: chicken, pasta, cream, garlic, parmesan, butter, salt, black pepper, nutmeg, parsley. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Salt a pot of boiling water generously; cook pasta until just shy of al dente, reserving a mug of pasta water.',
        'In a wide pan, build your sauce (garlic, tomato, cream, or butter) and simmer until cohesive.',
        'Toss pasta with sauce, splashing in pasta water to loosen; finish with cheese or herbs and serve hot.',
    ],
    'Chicken Burrito Bowl': [
        'Cook rice; keep warm. Season chicken; cook through; rest and slice.',
        'Warm black beans with cumin and salt; warm corn.',
        'Prep avocado, cilantro, lime, cheese, sour cream.',
        'Layer rice, chicken, beans, corn, and toppings.',
        'Finish with lime and cilantro.',
    ],
    'Chicken Caesar Wrap': [
        'Gather and prep: chicken, tortilla, lettuce, caesar dressing, parmesan, salt, black pepper, lemon juice, olive oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Chicken Cauliflower Rice Bowl': [
        'Gather and prep: chicken, cauliflower rice, broccoli, garlic, olive oil, gf soya sauce, ginger, salt, black pepper, green onions, sesame oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Chicken Lettuce Wrap': [
        'Mince garlic; slice green onions.',
        'Heat vegetable oil in a skillet on medium-high; cook ground chicken until no pink remains, breaking it up.',
        'Add garlic, most green onions, hoisin, gf soya sauce, sesame oil, and a splash of water; simmer until saucy, 3–5 minutes.',
        'Taste; adjust salt or gf soya sauce; cool slightly so lettuce does not wilt.',
        'Separate lettuce into cups; spoon filling in; top with remaining green onions; serve.',
    ],
    'Chicken Lettuce Wraps': [
        'Mince garlic; slice green onions; drain and finely dice water chestnuts.',
        'Heat vegetable oil in a skillet on medium-high; cook ground chicken until no pink remains, breaking it up.',
        'Add garlic, most green onions, hoisin, gf soya sauce, sesame oil, and a splash of water; simmer until saucy, 3–5 minutes.',
        'Taste; adjust salt or gf soya sauce; cool slightly so lettuce does not wilt.',
        'Separate lettuce into cups; spoon filling in; top with remaining green onions; serve.',
    ],
    'Chicken Noodle Soup': [
        'Gather and prep: chicken, noodles, carrots, celery, chicken broth, onion, garlic, bay leaves, salt, black pepper, fresh parsley. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Warm a little oil or butter; soften aromatics (onion, celery, garlic) until fragrant.',
        'Add broth and main solids; simmer until tender. If using noodles, add them with enough time to cook through.',
        'Season to taste, then ladle hot bowls and finish with any fresh herbs or cheese on your list.',
    ],
    'Chicken Salad Snack Box': [
        'Dice cooked chicken; mix with Greek yogurt, mayonnaise, celery, halved grapes, lemon juice, salt, and pepper.',
        'Chill 20 minutes for flavors to blend.',
        'Pack with rice cakes in a divided container.',
        'Keep refrigerated until snack time.',
    ],
    'Chicken Stir Fry': [
        'Gather and prep: chicken, broccoli, gf soya sauce, garlic, bell peppers, vegetable oil, ginger, cornstarch, sesame oil, salt, green onions. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat a wok or large skillet until very hot; add oil and sear protein in batches if needed so it browns.',
        'Add vegetables from firmest to softest, tossing often; splash in gf soya sauce or other sauce ingredients to glaze.',
        'Return protein, toss everything, taste for balance, and serve immediately over rice or noodles.',
    ],
    'Chicken Tomato Basil Bake': [
        'Gather and prep: chicken, tomatoes, basil, mozzarella, olive oil, garlic, salt, black pepper, balsamic vinegar, Italian seasoning. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    'Chicken Wings': [
        'Pat wings very dry. Mix baking powder, garlic powder, paprika, salt, and pepper; toss to coat evenly.',
        'Optional: rest uncovered on a rack in the fridge 1–4 hours for drier skin.',
        'Bake at 425–450°F (220–230°C) on a rack until deeply golden and crisp, flipping once, 40–50 minutes.',
        'Toss with hot sauce mixed with a little melted butter or oil for a sauced wing.',
        'Rest 3 minutes; serve warm.',
    ],
    'Chickpea Curry': [
        'Gather and prep: chickpeas, coconut milk, curry powder, tomatoes, onion, garlic, ginger, vegetable oil, salt, spinach. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Bloom spices or curry paste in oil until fragrant, then add sturdy vegetables or protein.',
        'Pour in coconut milk, tomatoes, or broth; simmer gently until flavors meld and ingredients are tender.',
        'Stir in quick-cook items (if any) at the end; taste, adjust salt/acid, and serve over rice or with bread.',
    ],
    'Chocolate Avocado Pudding Cups': [
        'Scoop avocado into a blender with cocoa, pitted dates, maple syrup, vanilla, salt, and almond milk.',
        'Blend until completely silky; scrape the sides once.',
        'Spoon into cups; chill at least 30 minutes.',
        'Top with a few cocoa nibs or berries if you have them.',
    ],
    'Chocolate Chip Waffles': [
        'Gather and prep: flour, milk, eggs, chocolate chips, butter, baking powder, sugar, salt, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix wet and dry separately, then combine until *just* mixed—small lumps are fine for fluffy pancakes/waffles.',
        'Preheat griddle or waffle iron; grease lightly. Cook in batches until bubbles set on top and bottoms are golden.',
        'Stack and serve with toppings from your list while warm.',
    ],
    'Chocolate Granola': [
        'Gather and prep: oats, brown sugar, cocoa powder, almonds, chocolate chunks, honey, coconut oil, salt, vanilla extract, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Chocolate-Strawberry Energy Bites': [
        'Gather and prep: oats, peanut butter, dark chocolate, freeze-dried strawberries, honey, vanilla extract, salt, chia seeds. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'Cinnamon Roll Oatmeal': [
        'Gather and prep: oats, milk, cinnamon, brown sugar, cream cheese, salt, butter, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Simmer oats with liquid (water or milk) until creamy, stirring often so nothing sticks.',
        'Stir in spices, fruit, or sweeteners in the last few minutes to preserve texture.',
        'Spoon into bowls and finish with toppings from your list.',
    ],
    'Cinnamon Roll Snowmen': [
        'Gather and prep: cinnamon roll dough, icing, sprinkles, candy eyes, food coloring, butter, powdered sugar. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Cinnamon Toast Crunch Muffins': [
        'Gather and prep: spice cake mix, pumpkin puree, cinnamon toast crunch, brown sugar, butter, eggs, water, vegetable oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Coconut Chia Mango Bowl': [
        'Gather and prep: chia seeds, coconut milk, mango, honey, coconut flakes, vanilla extract, lime. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Coconut Chickpea Curry': [
        'Gather and prep: chickpeas, coconut milk, curry powder, tomatoes, onion, garlic, ginger, vegetable oil, salt, spinach. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Bloom spices or curry paste in oil until fragrant, then add sturdy vegetables or protein.',
        'Pour in coconut milk, tomatoes, or broth; simmer gently until flavors meld and ingredients are tender.',
        'Stir in quick-cook items (if any) at the end; taste, adjust salt/acid, and serve over rice or with bread.',
    ],
    'Cottage Cheese Snack Bowl': [
        'Spoon cottage cheese into a bowl.',
        'Top with halved tomatoes, cucumber, basil, olive oil, salt, and pepper.',
        'Add cracked black pepper generously if you like savory punch.',
        'Eat cold; great post-workout.',
    ],
    'Crispy Sweet Potato Chips': [
        'Slice sweet potato very thinly with a mandoline if you have one; toss with cornstarch, then oil, paprika, garlic powder, salt, and pepper.',
        'Bake in a single layer at 400°F (200°C), flipping once, until crisp at the edges—watch closely near the end.',
        'Drain on a rack; sprinkle salt while warm.',
        'Best the day they are made.',
    ],
    'Crudi-Tots Platter': [
        'Gather and prep: tater tots, carrots, cucumber, bell peppers, dip, ranch dressing, salt, cherry tomatoes. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Easy Cherry Almond Granola Bars': [
        'Gather and prep: oats, dried cherries, almonds, honey, butter, brown sugar, vanilla extract, salt, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Easy Homemade Pickles': [
        'Gather and prep: cucumbers, vinegar, water, salt, sugar, garlic, dill, mustard seeds, black peppercorns. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Egg Muffins': [
        'Gather and prep: eggs, spinach, cheese, bell peppers, milk, salt, black pepper, onion powder. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk eggs with a pinch of salt until uniform; have fillings chopped and ready.',
        'Warm butter or oil in a nonstick pan; pour eggs and cook gently, lifting edges to let uncooked egg flow under.',
        'Add fillings, fold or roll, or bake in tins until just set; serve immediately.',
    ],
    'Egg Salad Lettuce Cups': [
        'Gather and prep: eggs, lettuce, mustard, olive oil, green onions, mayonnaise, salt, black pepper, paprika, celery, lemon juice. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Egg and Cheese Breakfast Sandwich': [
        'Gather and prep: bread, eggs, cheese, butter, milk, salt, black pepper, mayonnaise. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Five-Ingredient Golden Milk Snack Bites': [
        'Gather and prep: cashew butter, turmeric, maple syrup, coconut flakes, dates, cinnamon, black pepper, salt, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'French Toast': [
        'Gather and prep: bread, eggs, milk, cinnamon, maple syrup, butter, vanilla extract, salt, nutmeg. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Fresh Fruit Ice Pops': [
        'Gather and prep: fruit juice, fresh fruit, honey, water, vanilla, lemon juice, mint. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Fried Egg Rice Bowl': [
        'Gather and prep: rice, egg, green onions, gf soya sauce, sesame oil, vegetable oil, garlic, salt, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Frozen Yogurt Fruit Tubes': [
        'Blend Greek yogurt with mixed berries, honey, vanilla, and lemon until smooth.',
        'Pour into silicone popsicle molds or zip-top squeeze tubes designed for freezing.',
        'Freeze until solid.',
        'Thaw slightly before eating or pack in a cooler for a trip.',
    ],
    'Garlic Butter Shrimp Rice': [
        'Gather and prep: shrimp, rice, garlic, butter, lemon, chicken broth, salt, black pepper, parsley, white wine. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Garlic Parmesan Popcorn': [
        'Gather and prep: popcorn, butter, garlic, parmesan cheese, salt, black pepper, olive oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Combine or season components while dry ingredients are still easy to toss evenly.',
        'Bake, toast, or pop according to the snack—watch closely so nuts and sugars don’t burn.',
        'Cool slightly if needed for crunch, then serve in a bowl for snacking.',
    ],
    'Garlic Shrimp Quinoa Bowl': [
        'Gather and prep: shrimp, quinoa, garlic, spinach, lemon, butter, salt, black pepper, chicken broth, red pepper flakes. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Golden Oreo Truffles': [
        'Gather and prep: golden oreos, cream cheese, melted chocolate, vanilla, salt, powdered sugar, coconut oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'Granola with Milk': [
        'Gather and prep: granola, milk, berries, honey, nuts, banana, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Grated Egg Toast': [
        'Gather and prep: bread, avocado, eggs, salt, black pepper, olive oil, lemon juice, red pepper flakes, microgreens. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Greek Yogurt Berry Parfait': [
        'Gather and prep: yogurt, berries, honey, chia seeds, almonds, vanilla extract, granola. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Layer or soak components as the recipe suggests—chia often needs time in the fridge to thicken.',
        'Sweeten or spice to taste before final assembly.',
        'Top with fruit, granola, or nuts and serve chilled.',
    ],
    'Greek Yogurt Ranch Dip': [
        'Stir Greek yogurt with garlic powder, onion powder, dried dill, chives, salt, and pepper.',
        'Thin with a splash of lemon juice until dippable; taste and adjust seasoning.',
        'Chill 30 minutes for flavor to meld.',
        'Serve with cut vegetables or corn chips.',
    ],
    'Green Curry Chicken Thai': [
        'Cut chicken into bite-sized pieces; slice bell peppers; pick basil leaves.',
        'Heat oil; fry green curry paste 1–2 minutes until fragrant.',
        'Add chicken; cook until mostly opaque; pour in coconut milk; simmer until chicken is cooked through.',
        'Season with fish sauce, lime juice, and brown sugar to balance salty-sour-sweet.',
        'Add peppers until just tender; stir basil in off heat; serve with jasmine rice.',
    ],
    'Grilled Cheese Crostini': [
        'Gather and prep: bread, brie, strawberries, balsamic vinegar, mint, butter, honey, salt, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Grilled Salmon Bowl': [
        'Gather and prep: salmon, rice, cucumber, avocado, gf soya sauce, sesame oil, rice vinegar, salt, black pepper, sesame seeds, green onions. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Gwyneth Paltrow Blueberry Cauliflower Smoothie': [
        'Gather and prep: blueberries, cauliflower, almond milk, protein powder, ice, banana, honey, cinnamon. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Add liquids first, then soft fruit or veg, powders, and ice (if using) so the blender can move freely.',
        'Blend until silky, scraping down once if a chunk sticks. Thin with a splash of milk or water if needed.',
        'Taste and adjust sweetness, citrus, or salt; pour into a glass or bowl and enjoy right away.',
    ],
    'Ham and Cheese Omelette': [
        'Gather and prep: eggs, ham, cheese, milk, butter, salt, black pepper, chives. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk eggs with a pinch of salt until uniform; have fillings chopped and ready.',
        'Warm butter or oil in a nonstick pan; pour eggs and cook gently, lifting edges to let uncooked egg flow under.',
        'Add fillings, fold or roll, or bake in tins until just set; serve immediately.',
    ],
    'Hard-Boiled Egg Snack Pack': [
        'Cover eggs with cold water; bring to a boil, then simmer 9–11 minutes for firm yolks.',
        'Plunge into ice water; peel under cool running water.',
        'Halve or keep whole; season with everything seasoning and salt alongside tomatoes and cucumber.',
        'Pack chilled for the same day.',
    ],
    'Homemade Cheese Crackers': [
        'Gather and prep: cheddar cheese, parmesan cheese, flour, butter, salt, ice water, black pepper, paprika. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Combine or season components while dry ingredients are still easy to toss evenly.',
        'Bake, toast, or pop according to the snack—watch closely so nuts and sugars don’t burn.',
        'Cool slightly if needed for crunch, then serve in a bowl for snacking.',
    ],
    'Homemade Fruit Leather': [
        'Simmer apples and strawberries with honey, lemon, cinnamon, and a splash of water until very soft.',
        'Puree until smooth; spread thinly on a parchment-lined sheet pan.',
        'Dry in a low oven (about 140–170°F / 60–75°C) or dehydrator until leathery and not sticky in the center.',
        'Cool; slice into strips and roll with parchment backing.',
    ],
    'Homemade Trail Mix': [
        'Combine almonds, pumpkin seeds, dried cranberries, chocolate chips, coconut, and a tiny pinch of salt.',
        'Toss in a sealed bag until evenly mixed.',
        'Portion into small containers for the week.',
        'Store airtight at room temperature.',
    ],
    'Italian Deli Pinwheels (Turkey)': [
        'Gather and prep: flour tortillas, turkey, cheese, lettuce, mayonnaise, salt, black pepper, Italian seasoning, tomatoes. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Jammy Soft-Boiled Eggs': [
        'Gather and prep: eggs, ice water, salt, gf soya sauce, sesame seeds, green onions, rice vinegar. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Lemon Herb Salmon': [
        'Gather and prep: salmon, lemon, garlic, olive oil, parsley, salt, black pepper, dill, butter. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Lemon Oat Energy Balls': [
        'Pulse oats in a food processor until partly broken down; pit dates if needed.',
        'Add lemon zest and juice, honey, coconut, chia, vanilla, and a pinch of salt; blend until the mix sticks when squeezed.',
        'Roll into tight balls; chill 20–30 minutes so they firm up.',
        'Store in the fridge up to a week or freeze for longer.',
    ],
    'Lemon-y Avocado Toast': [
        'Gather and prep: bread, avocado, lemon, salt, olive oil, red pepper flakes, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Lentil Coconut Stew': [
        'Gather and prep: lentils, coconut milk, tomatoes, onion, curry powder, garlic, ginger, vegetable broth, salt, spinach, vegetable oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Bloom spices or curry paste in oil until fragrant, then add sturdy vegetables or protein.',
        'Pour in coconut milk, tomatoes, or broth; simmer gently until flavors meld and ingredients are tender.',
        'Stir in quick-cook items (if any) at the end; taste, adjust salt/acid, and serve over rice or with bread.',
    ],
    'Mango Yogurt Bowl': [
        'Gather and prep: yogurt, mango, granola, honey, coconut flakes, lime, chia seeds. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Layer or soak components as the recipe suggests—chia often needs time in the fridge to thicken.',
        'Sweeten or spice to taste before final assembly.',
        'Top with fruit, granola, or nuts and serve chilled.',
    ],
    'Mediterranean Chicken Salad': [
        'Gather and prep: chicken, cucumber, tomatoes, feta cheese, olive oil, lemon juice, red onion, oregano, salt, black pepper, kalamata olives, fresh mint. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Microwave Egg Snack Sandwich': [
        'Beat eggs with salt and pepper; microwave in a shallow greased dish in short bursts until just set, folding once.',
        'Toast the English muffin; melt cheese on one half if you like.',
        'Layer spinach and the cooked egg; close the sandwich.',
        'Eat warm within a few minutes for best texture.',
    ],
    'Mini Yogurt Cheesecakes': [
        'Gather and prep: graham crackers, greek yogurt, cream cheese, eggs, vanilla, sugar, salt, butter, lemon zest. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'One Pot Chicken Rice': [
        'Cut chicken into even pieces; season with salt and black pepper.',
        'Dice onion, mince garlic, rinse rice until water runs clearer; drain.',
        'Heat vegetable oil in a heavy pot on medium-high; brown chicken; remove.',
        'Sauté onion until soft; add garlic 30 seconds; toast rice 1–2 minutes.',
        'Return chicken; add chicken broth and water to the ratio your rice needs; bring to a boil.',
        'Cover, simmer on low until rice is tender and liquid is absorbed (about 18–25 minutes).',
        'Rest off heat 5 minutes; fluff with a fork; adjust salt; serve.',
    ],
    'One-Ingredient Watermelon Sorbet': [
        'Gather and prep: watermelon, fresh mint, lime juice. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Add liquids first, then soft fruit or veg, powders, and ice (if using) so the blender can move freely.',
        'Blend until silky, scraping down once if a chunk sticks. Thin with a splash of milk or water if needed.',
        'Taste and adjust sweetness, citrus, or salt; pour into a glass or bowl and enjoy right away.',
    ],
    'Overnight Oats Snack Jars': [
        'Stir oats with milk, chia, yogurt, honey, vanilla, and salt in a jar.',
        'Fold in some berries; seal and refrigerate overnight.',
        'Stir in the morning; add more fresh berries on top.',
        'Eat cold or warm slightly in the microwave.',
    ],
    'Pasta': [
        'Boil salted water; cook pasta to al dente; reserve 1 cup pasta water.',
        'Sauté garlic in olive oil on medium-low until fragrant (do not brown).',
        'Add tomato sauce; simmer 8–12 minutes; season with salt, pepper, and red pepper flakes.',
        'Toss pasta with sauce and a splash of pasta water; emulsify by tossing vigorously.',
        'Off heat, add basil and parmesan; add more pasta water if needed; serve hot.',
    ],
    'Peanut Butter Banana Toast': [
        'Gather and prep: bread, peanut butter, banana, honey, chia seeds, cinnamon, salt. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Toast or crisp bread/tortillas until golden where the recipe needs structure.',
        'Spread, layer, or fill with cheeses, proteins, and vegetables in even thickness.',
        'Finish (melt, press, broil, or roll), cut if needed, and serve while textures are at their best.',
    ],
    'Peanut Toffee Chocolate Clusters': [
        'Gather and prep: peanuts, chocolate, toffee bits, butter, salt, vanilla extract, corn syrup. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Mix binders (nut butter, honey, dates) with dry ingredients until the mixture holds when squeezed.',
        'Roll or press into portions; chill if the recipe needs them to firm up.',
        'Store airtight or serve straight from the fridge.',
    ],
    'Pizza Trail Mix': [
        'Gather and prep: nuts, sun-dried tomatoes, cheese crisps, italian seasoning, olive oil, garlic powder, salt, black pepper, parmesan cheese. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Combine or season components while dry ingredients are still easy to toss evenly.',
        'Bake, toast, or pop according to the snack—watch closely so nuts and sugars don’t burn.',
        'Cool slightly if needed for crunch, then serve in a bowl for snacking.',
    ],
    'Pumpkin Peanut Butter Oat Squares': [
        'Stir pumpkin, peanut butter, oats, honey, cinnamon, vanilla, salt, and nutmeg until uniform.',
        'Press firmly into a lined dish in an even layer.',
        'Refrigerate at least 1 hour until firm enough to slice (no-bake bar).',
        'Cut into squares; store chilled up to a week.',
    ],
    'Quick Yogurt Snack Bowl': [
        'Spoon Greek yogurt into a bowl.',
        'Top with berries, walnuts, cinnamon, honey, and a few chocolate chips.',
        'Stir gently or leave layered for crunch contrast.',
        'Serve right away.',
    ],
    'Quinoa Chickpea Salad': [
        'Gather and prep: quinoa, chickpeas, cucumber, tomatoes, olive oil, lemon juice, red onion, salt, black pepper, fresh parsley, feta cheese. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Rainbow Snack Mix': [
        'Gather and prep: white chocolate, pretzels, chex cereal, roasted nuts, dried berries, coconut oil, salt, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Ranch Popcorn Snack': [
        'Pop kernels your usual way (stovetop with a lid or air popper).',
        'Toss warm popcorn with melted butter, nutritional yeast, garlic and onion powder, parsley, salt, and pepper.',
        'Shake the bowl until every kernel looks lightly coated.',
        'Serve warm; store leftovers loosely covered so it stays crisp.',
    ],
    'Roasted Chickpeas': [
        'Gather and prep: chickpeas, olive oil, smoked paprika, garlic powder, sumac, salt, cumin, lemon juice. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Roasted Edamame': [
        'Gather and prep: edamame, olive oil, smoked paprika, lemon zest, salt, garlic powder, sesame seeds, gf soya sauce. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Roasted Pumpkin Seeds': [
        'Gather and prep: pumpkin seeds, olive oil, salt, curry powder, paprika, garlic powder, cayenne. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Roasted Veggie Chips': [
        'Gather and prep: sweet potato, olive oil, salt, herbs, black pepper, garlic powder, paprika. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Combine or season components while dry ingredients are still easy to toss evenly.',
        'Bake, toast, or pop according to the snack—watch closely so nuts and sugars don’t burn.',
        'Cool slightly if needed for crunch, then serve in a bowl for snacking.',
    ],
    'Salted Peanut Butter Cup Smoothie': [
        'Gather and prep: peanut butter, cocoa powder, almond milk, banana, sea salt, ice, honey, vanilla extract. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Add liquids first, then soft fruit or veg, powders, and ice (if using) so the blender can move freely.',
        'Blend until silky, scraping down once if a chunk sticks. Thin with a splash of milk or water if needed.',
        'Taste and adjust sweetness, citrus, or salt; pour into a glass or bowl and enjoy right away.',
    ],
    'Savory Breakfast Rice Bowl': [
        'Gather and prep: rice, eggs, gf soya sauce, green onions, sesame oil, vegetable oil, garlic, salt, sesame seeds. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Shrimp Avocado Cucumber Salad': [
        'Gather and prep: shrimp, avocado, cucumber, lime, olive oil, salt, black pepper, cilantro, red onion, jalapeño, garlic. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk or shake dressing ingredients until emulsified; taste for salt and acid.',
        'Toss greens or chopped vegetables with most of the dressing, adding delicate herbs or cheese last.',
        'Plate and finish with any crunch (nuts, seeds) or extra drizzle; serve chilled or room temp.',
    ],
    'Shrimp Fried Rice': [
        'Gather and prep: rice, shrimp, egg, peas, gf soya sauce, vegetable oil, garlic, green onions, sesame oil, salt, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Shrimp Garlic Butter Pasta': [
        'Gather and prep: shrimp, pasta, garlic, butter, parsley, salt, black pepper, lemon, olive oil, white wine. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Salt a pot of boiling water generously; cook pasta until just shy of al dente, reserving a mug of pasta water.',
        'In a wide pan, build your sauce (garlic, tomato, cream, or butter) and simmer until cohesive.',
        'Toss pasta with sauce, splashing in pasta water to loosen; finish with cheese or herbs and serve hot.',
    ],
    'Shrimp Tacos': [
        'Gather and prep: shrimp, tortillas, cabbage, lime, sauce, garlic, cumin, chili powder, salt, olive oil, cilantro, sour cream. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Silver Dollar Pancake Snacks': [
        'Whisk dry ingredients; whisk wet separately; combine until just mixed.',
        'Heat a griddle with butter; drop small spoonfuls for silver-dollar size.',
        'Flip when bubbles form; cook until golden on both sides.',
        'Stack with berries and maple syrup or pack cooled pancakes for later.',
    ],
    'Smoky Savory Fire Crackers': [
        'Gather and prep: saltine crackers, vegetable oil, ranch seasoning, red pepper flakes, garlic powder, onion powder, paprika, salt. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Combine or season components while dry ingredients are still easy to toss evenly.',
        'Bake, toast, or pop according to the snack—watch closely so nuts and sugars don’t burn.',
        'Cool slightly if needed for crunch, then serve in a bowl for snacking.',
    ],
    'Sourdough with Whipped Cottage Cheese and Raspberry Chia Jam': [
        'Gather and prep: sourdough bread, cottage cheese, raspberries, chia seeds, honey, lemon juice, vanilla extract, salt, butter. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Spicy Avocado Hummus': [
        'Gather and prep: chickpeas, avocado, tahini, garlic, cayenne, lemon juice, olive oil, salt, cumin, paprika. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Spinach Feta Breakfast Wrap': [
        'Gather and prep: tortilla, spinach, feta cheese, eggs, olive oil, salt, black pepper, red onion. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Spinach Mushroom Frittata': [
        'Gather and prep: eggs, spinach, mushrooms, onion, cheese, olive oil, salt, black pepper, garlic, milk. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Preheat the oven to the temperature that fits your dish (roughly 375–425°F / 190–220°C for many bakes).',
        'Par-cook or sear components on the stove if needed, then combine in your baking dish with sauces or eggs.',
        'Bake until set or golden and cooked through; rest a few minutes, then slice or scoop to serve.',
    ],
    'Strawberry Banana Smoothie Bowl': [
        'Gather and prep: strawberries, banana, yogurt, granola, honey, ice, milk, chia seeds. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Add liquids first, then soft fruit or veg, powders, and ice (if using) so the blender can move freely.',
        'Blend until silky, scraping down once if a chunk sticks. Thin with a splash of milk or water if needed.',
        'Taste and adjust sweetness, citrus, or salt; pour into a glass or bowl and enjoy right away.',
    ],
    'Stuffed Bell Peppers': [
        'Gather and prep: bell peppers, ground turkey, rice, tomatoes, onion, garlic, tomato sauce, Italian seasoning, salt, black pepper, mozzarella cheese, chicken broth. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Sweet Potato Fries': [
        'Gather and prep: sweet potato, olive oil, salt, paprika, garlic powder, cornstarch, black pepper, ketchup. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Sweet Potato White Bean Squares': [
        'Roast or microwave sweet potato until soft; mash with rinsed cannellini beans, oats, egg, maple syrup, cinnamon, vanilla, salt, and baking powder.',
        'Spread in a parchment-lined baking dish in an even layer.',
        'Bake at 350°F (175°C) until set and lightly golden; cool before cutting squares.',
        'Refrigerate extras; rewarm gently.',
    ],
    'Tacos': [
        'Dice onion. Brown ground turkey in oil; drain excess fat if needed.',
        'Add cumin, chili powder, garlic powder, salt, and a splash of water; simmer until saucy.',
        'Warm tortillas on a dry skillet or in foil in the oven.',
        'Fill with turkey, lettuce, cheese, salsa, and lime.',
        'Serve immediately.',
    ],
    'Tater Tot Nachos (Black Bean)': [
        'Gather and prep: tater tots, black beans, cheese, salsa, jalapeño, sour cream, green onions, cumin, lime, olive oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Thick Italian Hot Chocolate': [
        'Gather and prep: milk, bittersweet chocolate, cornstarch, sugar, vanilla, salt, cinnamon, whipped cream. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Tomato Basil Omelette': [
        'Gather and prep: eggs, tomatoes, basil, cheese, olive oil, salt, black pepper, butter, garlic. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk eggs with a pinch of salt until uniform; have fillings chopped and ready.',
        'Warm butter or oil in a nonstick pan; pour eggs and cook gently, lifting edges to let uncooked egg flow under.',
        'Add fillings, fold or roll, or bake in tins until just set; serve immediately.',
    ],
    'Turkey Cheddar Lettuce Roll Ups': [
        'Pat turkey slices dry; lay lettuce leaves flat and trim thick ribs.',
        'Spread a thin layer of mustard and mayonnaise; add turkey and cheddar strips.',
        'Roll tightly like a cigar; secure with a pick if needed.',
        'Slice into pinwheels or eat whole; keep chilled until serving.',
    ],
    'Turkey Cheese Apple Skewers': [
        'Cut turkey and cheese into cubes similar in size to apple chunks; toss apple with lemon juice to limit browning.',
        'Thread turkey, cheese, and apple onto small picks in repeating patterns.',
        'Season lightly with salt and pepper if you like.',
        'Serve immediately or pack chilled for the same day.',
    ],
    'Turkey Lettuce Snack Wraps': [
        'Layer butter lettuce with turkey, provolone strips, and thin bell pepper.',
        'Drizzle Italian dressing; season lightly with salt and pepper.',
        'Roll tightly; halve on a bias for easier eating.',
        'Serve immediately so lettuce stays crisp.',
    ],
    'Turkey Rice Bowl': [
        'Gather and prep: ground turkey, rice, spinach, carrots, garlic, gf soya sauce, sesame oil, ginger, salt, green onions, vegetable oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Vegan Banana Bread': [
        'Gather and prep: bananas, flour, flax egg, walnuts, plant milk, baking soda, baking powder, salt, sugar, vanilla extract, coconut oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Vegetable Fried Rice': [
        'Gather and prep: rice, eggs, carrots, peas, gf soya sauce, vegetable oil, garlic, green onions, sesame oil, salt, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Vegetable Pasta': [
        'Gather and prep: pasta, zucchini, tomato sauce, garlic, olive oil, salt, black pepper, red pepper flakes, parmesan cheese, fresh basil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Salt a pot of boiling water generously; cook pasta until just shy of al dente, reserving a mug of pasta water.',
        'In a wide pan, build your sauce (garlic, tomato, cream, or butter) and simmer until cohesive.',
        'Toss pasta with sauce, splashing in pasta water to loosen; finish with cheese or herbs and serve hot.',
    ],
    'Vegetable Stir-Fry': [
        'Prep vegetables; mince garlic and ginger. Mix cornstarch with cold water and gf soya sauce for a slurry.',
        'Heat vegetable oil in a wok on high until smoking-hot.',
        'Stir-fry carrots and broccoli first 2–3 minutes; add bell peppers; add garlic and ginger 30 seconds.',
        'Pour slurry around the pan; toss until glossy; adjust salt; drizzle sesame oil.',
        'Serve immediately over rice.',
    ],
    'Veggie Black Bean Nachos': [
        'Spread corn chips on a microwave-safe plate; warm beans with cumin and a pinch of salt.',
        'Layer beans, cheese, and jalapeño; microwave in bursts until cheese melts.',
        'Finish with salsa, sour cream, green onions, and a squeeze of lime.',
        'Eat immediately while chips are still crisp.',
    ],
    'Veggie Fried Rice': [
        'Gather and prep: rice, eggs, carrots, peas, gf soya sauce, vegetable oil, garlic, green onions, sesame oil, salt, black pepper. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook rice (or use leftover) while you sear proteins and vegetables in a hot pan with oil.',
        'Push ingredients aside to scramble eggs if using, then fold everything together with gf soya sauce and seasonings.',
        'Pile over rice, top with fresh bits (herbs, avocado), and serve warm.',
    ],
    'Veggie Omelette': [
        'Gather and prep: eggs, spinach, cheese, mushrooms, onion, butter, salt, black pepper, milk. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Whisk eggs with a pinch of salt until uniform; have fillings chopped and ready.',
        'Warm butter or oil in a nonstick pan; pour eggs and cook gently, lifting edges to let uncooked egg flow under.',
        'Add fillings, fold or roll, or bake in tins until just set; serve immediately.',
    ],
    'Veggie Quesadilla': [
        'Gather and prep: tortilla, cheese, bell peppers, onion, corn, butter, cumin, salt, black pepper, sour cream. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Cook fillings—seasoned meat, beans, or vegetables—until flavorful and any liquid has reduced.',
        'Warm tortillas or wraps briefly so they flex without cracking.',
        'Layer fillings, fold or roll tightly, slice if needed, and serve with salsa, lime, or extras on the side.',
    ],
    'Watermelon Salsa': [
        'Gather and prep: watermelon, jalapeño, lime, cilantro, red onion, salt, black pepper, cumin, olive oil. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
    'Zucchini Turkey Skillet': [
        'Gather and prep: ground turkey, zucchini, tomatoes, garlic, onion, olive oil, Italian seasoning, salt, black pepper, parmesan cheese, red pepper flakes. Wash produce, trim proteins, and chop or measure everything before you turn on the heat.',
        'Heat your main pan, pot, or oven to the right level for this dish before adding oil or butter.',
        'Cook in logical order—usually browning proteins or hardy veg first, then softer items—so everything finishes together.',
        'Combine, simmer, or toss as the recipe implies; taste and adjust salt, acid, or heat at the end.',
        'Plate while hot (or chill if meant cold) and enjoy!',
    ],
}
